@TV-Shows_HostAddress = https://localhost:7255

###

GET {{TV-Shows_HostAddress}}/platforms

###

POST {{TV-Shows_HostAddress}}/platforms

###

DELETE {{TV-Shows_HostAddress}}/platforms/{id}

###

GET {{TV-Shows_HostAddress}}/platforms/{id}

###

PUT {{TV-Shows_HostAddress}}/platforms/{id}

###

GET {{TV-Shows_HostAddress}}/shows

###

POST {{TV-Shows_HostAddress}}/shows

###

DELETE {{TV-Shows_HostAddress}}/shows/{id}

###

GET {{TV-Shows_HostAddress}}/shows/{id}

###

PUT {{TV-Shows_HostAddress}}/shows/{id}

###
